% ----------------------------------------------------------------------
%  MAIN PROGRAM - generated by the Rappture Builder
% ----------------------------------------------------------------------

% open the XML file containing the run parameters
% the file name comes in from the command-line via variable 'infile'
io = rpLib(infile);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Get input values from Rappture
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% get input value for input.string(Input)
Input = rpLibGetString(io,'input.string(Input).current');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Add your code here for the main body of your program
string='Why?'
pkg load optim
[fnm,path]=uigetfile('*.csv*','multiselect','off')
i=1
ff=fnm(i,:);
%filename=fullfile(path,cell2mat(ff))
 filename=fullfile(path,fnm);
fileID=fopen(filename,'r')
  dataArray=csvread(fileID);
fclose(fileID);
x=dataArray(:,1).';
y=dataArray(:,2).';

[xout,yout]=GpFit_Octave(x,y);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% spit out progress messages as you go along...
rpUtilsProgress(0, 'Starting...');
rpUtilsProgress(5, 'Loading data...');
rpUtilsProgress(50, 'Half-way there');
rpUtilsProgress(100, 'Done');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Save output values back to Rappture
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% save output value for output.curve(Raw)
% this assumes a vector 'x' and a vector 'y'
xydata = [x;y];
str = sprintf('%12g %12g\n', xydata);
rpLibPutString(io,'output.curve(Raw).component.xy',str,0);

% save output value for output.curve(Fit)
% this assumes a vector 'x' and a vector 'y'
xydata = [x;y];
str = sprintf('%12g %12g\n', xydata);
rpLibPutString(io,'output.curve(Fit).component.xy',str,0);

Rappture.result(io)

rpLibResult(io);
quit;
